# AUTOGENERATED! DO NOT EDIT! File to edit: Untitled.ipynb.

# %% auto 0
__all__ = ['model', 'title', 'description', 'article', 'predict']

# %% Untitled.ipynb 1
import gradio as gr
from transformers import pipeline

model = pipeline("text-generation")
title = "Ask Rick a Question"
description = """
The bot was trained to answer questions based on Rick and Morty dialogues. Ask Rick anything!
<img src="https://huggingface.co/spaces/course-demos/Rick_and_Morty_QA/resolve/main/rick.png" width=200px>
"""

article = "Check out [the original Rick and Morty Bot](https://huggingface.co/spaces/kingabzpro/Rick_and_Morty_Bot) that this demo is based off of."

def predict(prompt):
    completion = model(prompt)[0]["generated_text"]
    return completion
    
gr.Interface(
    fn=predict,
    inputs="textbox",
    outputs="text",
    title=title,
    description=description,
    article=article,
    examples=[["What are you doing?"], ["Where should we time travel to?"]],
).launch()
